src/Entity/Artiste.php
<?php

namespace App\Entity;

use App\Repository\ArtisteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArtisteRepository::class)]
class Artiste
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $photo;

    #[ORM\Column(type: 'text', nullable: true)]
    private $biographie;

    #[ORM\OneToMany(mappedBy: 'artiste', targetEntity: Concert::class)]
    private $concerts;

    public function __construct($nom="",$prenom="",$photo="",$biographie="")
    {
        $this->nom=$nom;
        $this->prenom=$prenom;
        $this->photo=$photo;
        $this->biographie=$biographie;
        $this->concerts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNomComplet(): ?string
    {
        return $this->prenom." ".$this->nom;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getBiographie(): ?string
    {
        return $this->biographie;
    }

    public function setBiographie(?string $biographie): self
    {
        $this->biographie = $biographie;

        return $this;
    }

    /**
     * @return Collection|Concert[]
     */
    public function getConcerts(): Collection
    {
        return $this->concerts;
    }

    public function addConcert(Concert $concert): self
    {
        if (!$this->concerts->contains($concert)) {
            $this->concerts[] = $concert;
            $concert->setArtiste($this);
        }

        return $this;
    }

    public function removeConcert(Concert $concert): self
    {
        if ($this->concerts->removeElement($concert)) {
            // set the owning side to null (unless already changed)
            if ($concert->getArtiste() === $this) {
                $concert->setArtiste(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getNomComplet();
    }


}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Concert;
use App\Entity\Email;
use App\Form\NewsletterType;
use App\Repository\ArtisteRepository;
use App\Repository\ConcertRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    #[Route('/', name: 'app_homepage')]
    public function concerts(ConcertRepository $cr): Response
    {
        $concerts = $cr->concertsAVenir();
        $concertsPasses = $cr->concertsPasses();
        return $this->render('default/concerts.html.twig', [
            'concerts' => $concerts,
            'concertsPasses' => $concertsPasses,

        ]);
    }



    #[Route("/concert/{id}", name: "app_concert")]
    public function voirConcert(Concert $concert): Response
    {
        return $this->render('default/concert.html.twig', [
            'concert' => $concert

        ]);
    }

    #[Route("/artistes", name: "app_artistes")]
    public function allArtistes(ArtisteRepository $artisteRepository): Response
    {
        return $this->render('default/artistes.html.twig', [
            'artistes' => $artisteRepository->findAll()

        ]);
    }


    #[Route("/newsletter", name: "app_newsletter")]
    public function formNewsletter(Request $request, EntityManagerInterface $em): Response
    {
        $email = new Email();
        $form = $this->createForm(NewsletterType::class, $email);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($email);
            $em->flush();
            return $this->redirectToRoute('app_homepage');
        }
        return $this->render('default/_formNewsletter.html.twig', ['form' => $form]);
    }
}

templates/default/_formNewsletter.html.twig
{# sous symfony 6, il n'y a plus besoin de passer par la methode createView pour les formulaires  #}
{{ form_start(form, {'action': path('app_newsletter'),'method': 'POST'}) }}
{{ form_label(form.email) }}
{{ form_widget(form.email) }}
<input type="submit" value="ok">
{{ form_end(form) }}

templates/default/artistes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les artistes{% endblock %}

{% block body %}
<main class="wrap">
    <header><h2>Ils sont passés à La Sirène</h2></header>
    <ul class="article">
        {% for artiste in artistes %}
        <li style="display: flex; justify-content: space-between; align-items: center; margin: 10px">{{ artiste.nomComplet }} <img src="{{ asset('assets/imgGroupes/'~artiste.photo) }}" alt="{{ artiste.nom }}"></li>
        {% endfor %}
    </ul>
</main>
{% endblock %}

templates/default/concert.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <main class="wrap">
        <article class="evenement">
            <header><h2>{{ concert.artiste.nom }}</h2></header>
            <h3 class="date">{{ concert.dateConcert | format_date('full', locale='fr') }}</h3>
            <img src="{{ asset('assets/imgGroupes/'~concert.artiste.photo) }}" alt="{{ concert.artiste.photo }}">
            <h4>{{ concert.artiste.prenom }} {{ concert.artiste.nom }}</h4>
            <p>{{ concert.description | raw}}</p>
            <h5>{{ concert.tarif }}€</h5>
        </article>
    </main>
{% endblock %}

templates/default/concerts.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <main class="wrap">
        <header><h2>Prochains concerts</h2></header>
        <ul class="listeEvenements">
            {% for concert in concerts %}
            <li class="evenement">
                <h3 class="date">{{ concert.dateConcert | format_date('full', locale='fr') }}</h3>
                <a href="{{ path('app_concert',{'id': concert.id }) }}">
                    <img src="{{ asset('assets/imgGroupes/'~concert.artiste.photo) }}" alt="{{ concert.artiste.nom }}">
                    <h4>{{ concert.artiste.prenom }} {{ concert.artiste.nom }}</h4>
                </a>
            </li>
            {% endfor %}
        </ul>
    </main>
    <aside class="wrap">
        <header><h2>Concerts passés</h2></header>
        <ul class="listeEvenements">
            {% for concert in concertsPasses %}
            <li class="evenement">
                <h3 class="date">{{ concert.dateConcert | format_date('full', locale='fr') }}</h3>
                <a href="{{ path('app_concert',{'id': concert.id }) }}">
                    <img src="{{ asset('assets/imgGroupes/'~concert.artiste.photo) }}" alt="{{ concert.artiste.nom }}">
                    <h4>{{ concert.artiste.prenom }} {{ concert.artiste.nom }}</h4>
                </a>
            </li>
            {% endfor %}
        </ul>
    </aside>
{% endblock %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/var/www/docker/tp4lp/src/Controller/DefaultController.php'|file_link(0) }}">src/Controller/DefaultController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/var/www/docker/tp4lp/templates/default/index.html.twig'|file_link(0) }}">templates/default/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}